title: Mason Weld # your name (or website title) here
# logo: "/images/ztest.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  <a href="https://www.linkedin.com/in/mason-weld-5b1817157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
