title: Mason Weld # your name (or website title) here
logo: "/images/rice-university-210464_1920.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my page!  This page contains my personal projects relating to data science and operations research.  My other skills, interests, and work experience can be found on my resume and LinkedIn below.

  I am currently looking for full-time employment in business/data analytics, operations research, and data science related positions following the completion of my Master's Degree in December 2020.
  <br><br>
  <a href="resume\Mason Weld Resume_2020.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/mason-weld-5b1817157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-173885598-1 # your Google Analytics tracking ID here
