title: Mason Weld # your name (or website title) here
logo: "/images/rice-university-210464_1920.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my page!  This is where a post solely my personal projects relating to data science and operations research.  My other skills, interests, and experience can be found on my resume and LinkedIn below.
  <br><br>
  I am currently looking for full time employment in operations research, analytics, data science following the completion of my Master's Degree in December 2020.
  <br><br>
  <a href="resume\Mason_Weld_Resume.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/mason-weld-5b1817157/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-173885598-1 # your Google Analytics tracking ID here
